vartotojas:
    resource: "@VartotojasBundle/Controller/"
    type:     annotation
    prefix:   /

preke:
    resource: "@PrekeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
