<?php

namespace VartotojasBundle\Repository;

/**
 * VartotojasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VartotojasRepository extends \Doctrine\ORM\EntityRepository
{
}
