<?php

namespace PrekeBundle\Repository;

/**
 * PrekeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrekeRepository extends \Doctrine\ORM\EntityRepository
{
}
